- name: Remove Kata Containers temp directory
  ansible.builtin.file:
    path: /tmp/kata_temp
    state: absent

- name: Remove BusyBox image
  ansible.builtin.command:
    cmd: ctr image remove docker.io/library/busybox:latest
  register: remove_result
  failed_when: remove_result.rc != 0 and 'no such image' not in remove_result.stderr
  changed_when: "'docker.io/library/busybox:latest: removed' in remove_result.stdout"
  ignore_errors: true
