name: ansible-lint
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  build:
    name: Ansible Lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Change working directory
      run: cd ansible

    - name: Run ansible-lint
      uses: ansible/ansible-lint@main
      with:
        working_directory: ansible
